name: Application PR Checks

on:
    pull_request:
    workflow_dispatch:

jobs:
    application_checks:
        name: Application checks
        uses: bonprix/backoffice-workflows/.github/workflows/application-checks.yml@main
