name: Dependabot Pull Request Approve and Merge

on: pull_request_target

jobs:
    dependabot:
        uses: bonprix/backoffice-workflows/.github/workflows/dependabot-approve-and-auto-merge.yml@main
