name: "Lint PR"

on:
    pull_request:
        types: [opened, edited, synchronize]

jobs:
    title:
        name: Validate PR title
        uses: bonprix/backoffice-workflows/.github/workflows/check-pr-title.yml@main
